### ISSUE TITLE
File paths are not using workspace variable.

### ISSUE THREAD

**Issue by georgeamccarthy** [georgeamccarthy/protein_search#11]
Jina has a workspace variable, from which we can construct file paths. See [line 93](https://github.com/jina-ai/jina/blob/master/jina/helloworld/chatbot/my_executors.py).

Currently relative imports are used which require running from the `/backend` directory. [line ](https://github.com/georgeamccarthy/protein_search/blob/main/backend/app.py), [line 70](https://github.com/georgeamccarthy/protein_search/blob/add_indexer_flow/backend/my_executors.py)

If app.py is run from the /protein_search directory by `python backend/app.py` then the error is thrown:
`Traceback (most recent call last):
  File "/Users/georgeamccarthy/Documents/workspace/python/protein_search/protein_search/backend/app.py", line 20, in <module>
    main()
  File "/Users/georgeamccarthy/Documents/workspace/python/protein_search/protein_search/backend/app.py", line 9, in main
    fp=open("../data/samelength.csv"),
FileNotFoundError: [Errno 2] No such file or directory: '../data/samelength.csv'`

**Comment by fissoreg** [comment]
After today's discussion, it appears like we should just get rid of the `workspace` variable. This is addressed in #17

For proper directories management, see #18
