### ISSUE TITLE
MyIndexer tests are failing because a flow has not been opened.

### ISSUE THREAD

**Issue by georgeamccarthy** [georgeamccarthy/protein_search#21]
**Describe the bug**
MyIndexer tests are failing because a flow has not been opened.

**To Reproduce**
1. `make test`
2. see error

**Expected behavior**
Pass tests

**Additional context**
I think these tests run methods on MyIndexer() without instantiating an object. This means self.workspace is not set. Instead use:
```
with flow:
    flow.index(...)...
```

**Comment by fissoreg** [comment]
Fixed in #22
