### ISSUE TITLE
Extend indexing to more proteins

### ISSUE THREAD

**Issue by georgeamccarthy** [georgeamccarthy/protein_search#28]
**Is your feature request related to a problem? Please describe.**
- [Currently only 42 proteins are being indexed.](https://github.com/georgeamccarthy/protein_search/blob/b0e0bbe31301c1c91abb6449dfa9eeed757cb3ea/backend/app.py#L25)
- We want to index more proteins. If computationally feasible we will index [the entire dataset which includes 10,000 proteins.](https://github.com/georgeamccarthy/protein_search/blob/b0e0bbe31301c1c91abb6449dfa9eeed757cb3ea/backend/backend_config.py#L5)

**Describe the solution you'd like**
### Option 1 - theoretical computation time
- Figure out how much time each additional protein adds to encoding time. E.g. try with 20/50/100 proteins and measure the difference.
- Calculate the time to index 10,000 proteins.

### Option 2 - attempt to compute
- Try to compute all 10,000 on our machines and see if it will complete in a few hours. @fissoreg Can you try this? Currently my machine is taking too long to compute the embeddings, probably due to a bug - see #27. I recall that you can compute the 42 quite quickly.

**Comment by georgeamccarthy** [comment]
@fissoreg let's disable `flow.block()` and run `backend/app.py` with **42** proteins and compare our computation time.

My output was:
```python backend/app.py  190.66s user 8.11s system 102% cpu 3:13.73 total```

**Comment by fissoreg** [comment]
Here is my time:
`python backend/app.py  179.57s user 34.62s system 302% cpu 1:10.85 total`

Not a big difference, if I correctly interpret the numbers. It just seems like more cores are used on my PCs.

**Comment by georgeamccarthy** [comment]
Could you share your CPU, RAM and GPU specs please?

**Comment by fissoreg** [comment]
Nothing exceptional:
- Intel i5 @2.80 GHz (4 cores)
- 16 GB RAM
- no GPU

I guess this conversation is relevant for #27

**Comment by georgeamccarthy** [comment]
Closing as it looks like the indexing up to 100k proteins should be feasible on low-mid spec hardware.
