### ISSUE TITLE
feat: improve indexing flow

### ISSUE THREAD

**Issue by georgeamccarthy** [georgeamccarthy/protein_search#43]
- The indexing flow is making use of code from the chat bot example.
- Change this to make use of cleaner, more efficient indexers for the application.

References
- [AnnoyIndexer](https://github.com/jina-ai/jina-hub/blob/master/indexers/vector/AnnoyIndexer/README.md)

**Comment by fissoreg** [comment]
Just a note: #48 doesn't implement the indexer.

**Comment by georgeamccarthy** [comment]
Could shout, I'll open a new issue for investigating indexers.
