### ISSUE TITLE
feat: use another indexing protocol to http

### ISSUE THREAD

**Issue by georgeamccarthy** [georgeamccarthy/protein_search#47]
feat: use another indexing protocol to http

[Slack convo](https://jina-ai.slack.com/archives/C0169V26ATY/p1627573136319000?thread_ts=1627572153.318800&cid=C0169V26ATY)
> Deepankar (Jina AI) 
> Is there a reason you want to use http protocol during indexing? That'd be significantly slower than grpc or websockets.

@fissoreg

**Comment by fissoreg** [comment]
Seen the convo, I would be happy to switch to gRPC. I'll look into that!

This would also solve #45.

**Comment by georgeamccarthy** [comment]
Great!

**Comment by fissoreg** [comment]
Done in #50.
